---
- name: "Setup"
  hosts: webservers
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present

    - name: enable and start nginx
      service:
        name: nginx
        enabled: yes
        state: started
